// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBLWYSPTkl7Z0UUkSkT6I0WoLF-kfEcX8',
    appId: '1:145731753978:web:1897800044234c6beff643',
    messagingSenderId: '145731753978',
    projectId: 'notes-2022-flutter',
    authDomain: 'notes-2022-flutter.firebaseapp.com',
    storageBucket: 'notes-2022-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhj2ezAZTb2cb7DBjKKO7VFSYjrRYuzLA',
    appId: '1:145731753978:android:8cd299d561713a55eff643',
    messagingSenderId: '145731753978',
    projectId: 'notes-2022-flutter',
    storageBucket: 'notes-2022-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-ZXp9CKkwTGAGC__tZCbCXANTuxKLmZo',
    appId: '1:145731753978:ios:9f5571157f91f317eff643',
    messagingSenderId: '145731753978',
    projectId: 'notes-2022-flutter',
    storageBucket: 'notes-2022-flutter.appspot.com',
    iosClientId: '145731753978-7btrikbl6jbq26733vobsf6euf5e051p.apps.googleusercontent.com',
    iosBundleId: 'com.wanubit.notes',
  );
}
